version: 2.1

references:
  
  workspace_root: &workspace_root
    /tmp/workspace
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  
  Code-Scan:
    docker: 
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout # check out source code to working directory
      - run: shiftleft -D code-scan -s ./

  IaC-Assessment:
    docker:
      - image: checkpoint/shiftleft:latest
    steps:
      - checkout
      - run: shiftleft -D iac-assessment -p ./terraform-template -r -64 -s medium || true

workflows:
  version: 2
  ShiftLeft_Demo_Pipeline:
    jobs:
      - Code-Scan
      - IaC-Assessment          
